version: "3.8"

services:
  backend:
    image: juwono136/myjekid-api:latest
    pull_policy: always
    container_name: myjekid-api
    restart: always
    environment:
      # SERVER CONFIG
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}

      # EMAIL CONFIG
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

      # DATABASE CONFIG
      DATABASE_URL: ${DATABASE_URL}

      # WAHA CONFIG
      WAHA_API_URL: ${WAHA_API_URL}
      WAHA_API_KEY: ${WAHA_API_KEY}

      # MINIO CONFIGURATION
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PORT: ${S3_PORT}
      S3_USE_SSL: ${S3_USE_SSL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      BASE_IMAGE_URL: ${BASE_IMAGE_URL}

      # REDIS CONFIG
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # AI CONFIGURATION
      AI_PROVIDER: ${AI_PROVIDER}

      # API KEYS FOR AI MODELS
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # OLLAMA CONFIG (Local)
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}

      # LMSTUDIO CONFIG (Local)
      LMSTUDIO_BASE_URL: ${LMSTUDIO_BASE_URL}
      LMSTUDIO_MODEL: ${LMSTUDIO_MODEL}
      LMSTUDIO_API_KEY: ${LMSTUDIO_API_KEY}
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tunnel

  frontend:
    image: juwono136/myjekid-frontend:latest
    pull_policy: always
    container_name: myjekid-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - tunnel

networks:
  tunnel:
    external: true
